apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zr93be159-go
  janus-idp.io/tekton: zr93be159-go
  backstage.io/kubernetes-id: zr93be159-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zr93be159-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
